django_project/commercial/urls.py
from django.conf.urls import include
from django.urls.conf import re_path
from rest_framework import routers

from .views import ProductViewSet, ProductsListView, ProductsUpdateView, ProductCreateView, product_import, store_create, category_create, ProductView, ProductsBuyView

app_name = 'commercial'

router = routers.DefaultRouter()
router.register(r'product_list', ProductViewSet)

urlpatterns = [
    re_path('^api/', include(router.urls)),
    re_path('^ajax/post/product/(?P<pk>\d+)/$', ProductsUpdateView.as_view(), name="ajax-product-post"),
    re_path('^product/create/$', ProductCreateView.as_view(), name="product-create"),
    re_path('^product/import/$', product_import, name="product-import"),
    re_path('^store/create/$', store_create, name="store-create"),
    re_path('^category/create/$', category_create, name="category-create"),
    re_path('^products/$', ProductView.as_view(), name="products"),
    re_path('^product/buy/(?P<pk>\d+)/$', ProductsBuyView.as_view(), name="products-buy"),
    re_path('', ProductsListView.as_view(), name="home"),
]

django_project/django_project/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls.conf import re_path

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path("accounts/", include("django.contrib.auth.urls")),
    re_path("", include("commercial.urls"))
]

django_project/commercial/models.py
from django.db import models


# Create your models here.

class Store(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class ProductAvailability(models.IntegerChoices):
    AVAILABLE = 1, "Available"
    NOT_AVAILABLE = 2, "Not Available"


class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=10)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    description = models.CharField(max_length=100, null=True, blank=True)
    availability = models.IntegerField(choices=ProductAvailability.choices)

    def __str__(self):
        return self.name

    def is_available(self):
        return self.availability == ProductAvailability.AVAILABLE and self.quantity > 0

django_project/commercial/views.py
import json

from django.db.models.expressions import F
from django.http.response import JsonResponse
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from rest_framework import viewsets, status
from rest_framework.views import APIView
from tablib.core import Dataset

from .models import Product, ProductAvailability, Store, Category
from .resources import ProductResource
from .serializer import ProductSerializer, StoreSerializer, CategorySerializer


class ProductsListView(ListView):
    template_name = 'home.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context["availability"] = json.dumps(dict(ProductAvailability.choices))
        context["stores"] = json.dumps(dict(Store.objects.all().values_list('id', 'name')))
        context["categories"] = json.dumps(dict(Category.objects.all().values_list('id', 'name')))
        return context


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class ProductsUpdateView(APIView):
    serializer_class = ProductSerializer

    def post(self, request, **kwargs):
        product = Product.objects.get(id=kwargs.get("pk"))
        serializer = self.serializer_class(product, data=request.data)
        if not serializer.is_valid():
            print(serializer.errors)
            return JsonResponse({"success": False, "error": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
        serializer.save()
        return JsonResponse({"success": True}, status=200)


class ProductsBuyView(APIView):
    serializer_class = ProductSerializer

    def get(self, request, **kwargs):
        Product.objects.filter(id=kwargs.get("pk")).update(quantity=F('quantity') - 1)
        return JsonResponse({"success": True}, status=200)


class ProductCreateView(APIView):
    serializer_class = ProductSerializer

    def post(self, request, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if not serializer.is_valid():
            print(serializer.errors)
            return JsonResponse({"success": False, "error": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
        serializer.save()
        return JsonResponse({"success": True}, status=200)


class ProductView(TemplateView):
    template_name = "products.html"

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context["products"] = Product.objects.filter(availability=ProductAvailability.AVAILABLE, quantity__gt=0)
        print(context["products"])
        return context


def product_import(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.method == "POST":
        new_products = request.FILES['file']
        product_resource = ProductResource()
        dataset = Dataset().load(new_products.read())
        try:
            result = product_resource.import_data(dataset, dry_run=True, raise_errors=True)
        except Exception as e:
            return JsonResponse({"success": False, "error": str(e)}, status=400)
        if not result.has_errors():
            product_resource.import_data(dataset, dry_run=False)
            return JsonResponse({"success": True}, status=200)
        print(result)
    return JsonResponse({"error": ""}, status=400)


def store_create(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.method == "POST":
        create_store_data = json.loads(request.POST.get("create_store_data"))
        serializer = StoreSerializer(data=create_store_data)
        if not serializer.is_valid():
            print(serializer.errors)
            return JsonResponse({"error": serializer.errors}, status=400)
        serializer.save()
        return JsonResponse({"success": True}, status=200)
    return JsonResponse({"error": ""}, status=400)


def category_create(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.method == "POST":
        create_category_data = json.loads(request.POST.get("create_category_data"))
        serializer = CategorySerializer(data=create_category_data)
        if not serializer.is_valid():
            print(serializer.errors)
            return JsonResponse({"error": serializer.errors}, status=400)
        serializer.save()
        return JsonResponse({"success": True}, status=200)
    return JsonResponse({"error": ""}, status=400)

django_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block style %}
    {% endblock %}

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Products</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'commercial:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'commercial:products' %}">View Products</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% if user.is_authenticated %}
        {% block content %}
        {% endblock %}
    {% else %}
        <p>You are not logged in</p>
        {% block logout_content %}
        {% endblock %}
    {% endif %}

    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

django_project/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Products List{% endblock %}

{% block content %}
  <div class="container">
    <br>
    <div class="row">
        <div class="col-sm-12">
            <button id="import-product-button" class="btn btn-primary" type="button" name="button">Import Products</button>
            <button id="create-store-button" class="btn btn-primary" type="button" name="button">Create Store</button>
            <button id="create-category-button" class="btn btn-primary" type="button" name="button">Create Category</button>
        </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-12">
        <table id="datatable" class="table table-striped table-bordered" style="width:100%" data-server-side="true">
          <thead>
            <tr>
              <th data-data="id">#</th>
              <th data-data="name">Name</th>
              <th data-data="quantity">Quantity</th>
              <th data-data="price">Price</th>
              <th data-data="description">Description</th>
              <th data-data="category">Category</th>
              <th data-data="store">Store</th>
              <th data-data="availability">Availability</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>


  <div class="modal fade" id="import_product" role="dialog">
      <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
              <div class="modal-header">
                  <h3 class="modal-title">New Product</h3>
              </div>
              <div class="modal-body">
                    <form method="post" id="import-product-form" enctype="multipart/form-data">
                        <input type="file" name="myfile" id="product-file">
                        <button type="submit">Upload</button>
                    </form>
              </div>
          </div>
      </div>
  </div>

  <div class="modal fade" id="store_create" role="dialog">
      <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
              <div class="modal-header">
                  <h3 class="modal-title">New Store</h3>
              </div>
              <div class="modal-body">
                    <form method="post" id="store_create_form" enctype="multipart/form-data">
                        <input type="text" name="name" id="store-name">
                        <button type="submit">Save</button>
                    </form>
              </div>
          </div>
      </div>
  </div>

  <div class="modal fade" id="category_create" role="dialog">
      <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
              <div class="modal-header">
                  <h3 class="modal-title">New Category</h3>
              </div>
              <div class="modal-body">
                    <form method="post" id="category_create_form" enctype="multipart/form-data">
                        <input type="text" name="name" id="category-name">
                        <button type="submit">Save</button>
                    </form>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

{% block script %}
<script>
  var product_form_url = "{% url 'commercial:ajax-product-post' 0 %}";
  var product_create_url = "{% url 'commercial:product-create' %}";
  var product_import_url = "{% url 'commercial:product-import' %}";
  var store_create_url = "{% url 'commercial:store-create' %}";
  var category_create_url = "{% url 'commercial:category-create' %}";
  var csrf_token = "{{ csrf_token }}";
  var availability = "{{ availability|escapejs }}";
  var stores = "{{ stores|escapejs }}";
  var categories = "{{ categories|escapejs }}";
</script>
<script src='{% static "js/home.js" %}?v=1.0'></script>
{% endblock %}

django_project/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Products{% endblock %}

{% block style %}
<style>
.product-description {
    height: 50px;
}
</style>
{% endblock %}

{% block content %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
    	<div class="col-md-12">
            {% for product in products %}
			<div class="col-sm-6 col-md-4">
				<div class="thumbnail" >
					<h4 class="text-center"><span class="label label-info">{{ product.category.name }}</span></h4>
					<div class="caption">
						<div class="row">
							<div class="col-md-6 col-xs-6">
								<h3>{{ product.name }}</h3>
							</div>
							<div class="col-md-6 col-xs-6 price">
								<h3>
								<label>AED{{ product.price }}</label></h3>
							</div>
						</div>
						<p class="product-description">{{ product.description }}</p>
						<div class="row">
							<div class="col-md-6">
								<a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-thumbs-up"></span> Like</a>
							</div>
							<div class="col-md-6">
								<a href="#" class="buy btn btn-success btn-product" data-id="{{ product.id }}"><span class="glyphicon glyphicon-shopping-cart"></span> Buy</a></div>
						</div>

						<p> </p>
					</div>
				</div>
			</div>
            {% endfor %}
        </div>
	</div>

</div>
{% endblock %}

{% block script %}
<script>
	$(".buy").on("click", function() {
		var product_id = $(this).attr("data-id");
        $.ajax({
            type: 'GET',
            url: "{% url 'commercial:products-buy' 0 %}".replace('0', product_id),
            processData: false,
            contentType: false,
            success: function(response) {
                console.log("Success");
                window.location.reload();
            },
            error: function(response) {
                console.log(response);
            }
        });

	});
</script>
{% endblock %}